# --- Subtitles ---
g add sub-scale +0.1
f add sub-scale -0.1
t add sub-pos -1
r add sub-pos +1

# --- Seeking ---
RIGHT seek 2
LEFT seek -2
] playlist-next
[ playlist-prev

# --- Playback ---
= add speed 0.25
- add speed -0.25
UP add volume 1
DOWN add volume -1

# --- Scripts ---
# Toggle crop (vlccrop script)
c script-binding vlccrop/toggle_crop

# --- Ignore ---
w ignore
o ignore
p ignore
d ignore
j ignore
l ignore
v ignore
a ignore
