# --- General ---
profile=high-quality
keep-open=yes
save-position-on-quit=yes
autofit=50%
force-seekable=yes
loop=yes
osc=no
input-ipc-server=\\.\pipe\mpvsocket
demuxer-lavf-o=fflags=+genpts
alang=en,eng
volume-max=200

# --- Window ---
window-dragging=yes
border=yes
title-bar=no

# --- Screenshots ---
screenshot-sw=yes
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-jpeg-quality=95
screenshot-dir="E:\Virak\Pictures\Screenshots"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

# --- Subtitles ---
sub-font="NetflixSans-Medium"
sub-font-size=40
sub-bold=no
sub-pos=89
sub-border-size=2
sub-border-color="#000000"
sub-shadow-offset=2
sub-shadow-color="#80000000"
sub-blur=0.2
sub-fix-timing=yes
blend-subtitles=no
# Force your styling even on embedded ASS subs (optional)
sub-ass-override=force

# --- Font ---
osd-font="JetBrains Mono"
osd-border-size=1.6
osd-shadow-offset=1
osd-shadow-color="#80000000"