# Limit the number of subprocesses to launch asynchronously
proc_limit=4

# Limit the number of raw bgra thumbnail files extracted to disk.
# Note this does not include fragments. They are kept as long as the file is still playing.
raw_thumb_limit=64

# Temporary directory within which the thumbnail cache directory will be created
# Defaults to "$TMPDIR" or "/tmp". On windows defaults to %TEMP%, %TMP% or %LOCALAPPDATA%.
# tmpdir=/tmp

# Fetches all fragments immediately. This is usually faster due to curl
# being able to reuse connections. If disabled, fragments will be fetched
# only when they're needed, one curl invocation per fragment. Greedy mode
# is recommended unless you have severe bandwidth restrictions.
greedy_fetch=yes

# Change if this conflicts with another scripts
# see: https://github.com/mpv-player/mpv/issues/17534
overlay_id=32
